name: Docker Build Check

on:
  push:
    paths:
      - 'apps/api/sigma/Dockerfile'
      - '.github/workflows/docker-check.yml'
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf
        with:
          dockerfile: apps/api/sigma/Dockerfile

  build-docker:
    runs-on: ubuntu-latest
    needs: lint-docker
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: |
          docker build -f apps/api/sigma/Dockerfile -t api:ci-check .

      - name: Scan for vulnerabilities
        uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0
        with:
          image-ref: api:ci-check
          format: 'table'
